// Generated by gencpp from file phone/link.msg
// DO NOT EDIT!


#ifndef PHONE_MESSAGE_LINK_H
#define PHONE_MESSAGE_LINK_H

#include <ros/service_traits.h>


#include <phone/linkRequest.h>
#include <phone/linkResponse.h>


namespace phone
{

struct link
{

typedef linkRequest Request;
typedef linkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct link
} // namespace phone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phone::link > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::phone::link&) { return value(); }
};

template<>
struct DataType< ::phone::link > {
  static const char* value()
  {
    return "phone/link";
  }

  static const char* value(const ::phone::link&) { return value(); }
};


// service_traits::MD5Sum< ::phone::linkRequest> should match
// service_traits::MD5Sum< ::phone::link >
template<>
struct MD5Sum< ::phone::linkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phone::link >::value();
  }
  static const char* value(const ::phone::linkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phone::linkRequest> should match
// service_traits::DataType< ::phone::link >
template<>
struct DataType< ::phone::linkRequest>
{
  static const char* value()
  {
    return DataType< ::phone::link >::value();
  }
  static const char* value(const ::phone::linkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phone::linkResponse> should match
// service_traits::MD5Sum< ::phone::link >
template<>
struct MD5Sum< ::phone::linkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phone::link >::value();
  }
  static const char* value(const ::phone::linkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phone::linkResponse> should match
// service_traits::DataType< ::phone::link >
template<>
struct DataType< ::phone::linkResponse>
{
  static const char* value()
  {
    return DataType< ::phone::link >::value();
  }
  static const char* value(const ::phone::linkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHONE_MESSAGE_LINK_H
