// Generated by gencpp from file phone/linux.msg
// DO NOT EDIT!


#ifndef PHONE_MESSAGE_LINUX_H
#define PHONE_MESSAGE_LINUX_H

#include <ros/service_traits.h>


#include <phone/linuxRequest.h>
#include <phone/linuxResponse.h>


namespace phone
{

struct linux
{

typedef linuxRequest Request;
typedef linuxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct linux
} // namespace phone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phone::linux > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::phone::linux&) { return value(); }
};

template<>
struct DataType< ::phone::linux > {
  static const char* value()
  {
    return "phone/linux";
  }

  static const char* value(const ::phone::linux&) { return value(); }
};


// service_traits::MD5Sum< ::phone::linuxRequest> should match
// service_traits::MD5Sum< ::phone::linux >
template<>
struct MD5Sum< ::phone::linuxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phone::linux >::value();
  }
  static const char* value(const ::phone::linuxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phone::linuxRequest> should match
// service_traits::DataType< ::phone::linux >
template<>
struct DataType< ::phone::linuxRequest>
{
  static const char* value()
  {
    return DataType< ::phone::linux >::value();
  }
  static const char* value(const ::phone::linuxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phone::linuxResponse> should match
// service_traits::MD5Sum< ::phone::linux >
template<>
struct MD5Sum< ::phone::linuxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phone::linux >::value();
  }
  static const char* value(const ::phone::linuxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phone::linuxResponse> should match
// service_traits::DataType< ::phone::linux >
template<>
struct DataType< ::phone::linuxResponse>
{
  static const char* value()
  {
    return DataType< ::phone::linux >::value();
  }
  static const char* value(const ::phone::linuxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHONE_MESSAGE_LINUX_H
