// Generated by gencpp from file phone/linuxResponse.msg
// DO NOT EDIT!


#ifndef PHONE_MESSAGE_LINUXRESPONSE_H
#define PHONE_MESSAGE_LINUXRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phone
{
template <class ContainerAllocator>
struct linuxResponse_
{
  typedef linuxResponse_<ContainerAllocator> Type;

  linuxResponse_()
    : sum(0)  {
    }
  linuxResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::phone::linuxResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phone::linuxResponse_<ContainerAllocator> const> ConstPtr;

}; // struct linuxResponse_

typedef ::phone::linuxResponse_<std::allocator<void> > linuxResponse;

typedef boost::shared_ptr< ::phone::linuxResponse > linuxResponsePtr;
typedef boost::shared_ptr< ::phone::linuxResponse const> linuxResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phone::linuxResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phone::linuxResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::phone::linuxResponse_<ContainerAllocator1> & lhs, const ::phone::linuxResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::phone::linuxResponse_<ContainerAllocator1> & lhs, const ::phone::linuxResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace phone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::phone::linuxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phone::linuxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phone::linuxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phone::linuxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phone::linuxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phone::linuxResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phone::linuxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::phone::linuxResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::phone::linuxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phone/linuxResponse";
  }

  static const char* value(const ::phone::linuxResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phone::linuxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 sum\n"
;
  }

  static const char* value(const ::phone::linuxResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phone::linuxResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct linuxResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phone::linuxResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phone::linuxResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHONE_MESSAGE_LINUXRESPONSE_H
