<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="PI" value="3.1415926"/>
    <xacro:property name="radius" value="0.1"/>
    <xacro:property name="footprint" value="0.001"/>
    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_lenth" value="0.013"/>
    <xacro:property name="hight" value="0.015"/>
    <xacro:property name="base_lenth" value="0.08"/>

    <xacro:property name="wheel_joint_z" value="${-1*(base_lenth/2.0 -wheel_radius + hight)}"/>


    <link name = "base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint}" />
            </geometry>
        </visual>
    </link> 

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${radius}" length="${base_lenth}" />
            </geometry>         
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="BL_clolor">
                <color rgba="1.0 0.5 0.2 0.5" />
            </material>
        </visual>
        <collision>
         <geometry>
                <cylinder radius="${radius}" length="${base_lenth}" />
        </geometry>         
        <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertial_matrix m="5" r="${radius}" h="${base_lenth}"/>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="L1" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${hight+base_lenth/2.0}" />
    </joint>

<xacro:macro name="mk_wheel" params="wheel_name flag1 flag2">
     <link name="${wheel_name}_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${PI*flag2*flag2/2.0} ${PI*flag1*flag1/2.0} 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_lenth}" />
            </geometry>
            <material name="wheel_color">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
    <collision>
         <geometry>
                <cylinder radius="${wheel_radius}" length="${base_lenth}" />
        </geometry>         
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
        <xacro:cylinder_inertial_matrix m="0.6" r="${wheel_radius}" h="${wheel_lenth}"/>
    </link>
    <gazebo reference="${wheel_name}_wheel">
        <material>Gazebo/Red</material>
    </gazebo>
                
    <joint name="${wheel_name}2link" type="continuous">
        <parent link="base_link" />
        <child link="${wheel_name}_wheel" />
        <origin xyz="${(radius+wheel_lenth/2.0)*flag1} ${(radius+wheel_lenth/2.0)*flag2} ${wheel_joint_z}" rpy="0 0 0" />
        <axis xyz="${flag1} ${-flag2} 0" />
    </joint>
</xacro:macro>

    <xacro:mk_wheel wheel_name="l" flag1="0.0" flag2="1.0"/>
    <xacro:mk_wheel wheel_name="r" flag1="0.0" flag2="-1.0"/>

<link name="ball1">
        <visual>
            <geometry>
             <sphere radius="${hight/2}" />
            </geometry>         
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="BL_clolor">
                <color rgba="0.0 0.5 0.2 0.8" />
            </material>
        </visual>
        <collision>
        <geometry>
             <sphere radius="${hight/2}" />
            </geometry>         
        <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:sphere_inertial_matrix m="1" r="${hight/2}" />
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="L5" type="continuous">
        <parent link="base_link" />
        <child link="ball1" />
        <origin xyz="${radius} 0 ${-hight/2.0-base_lenth/2.0}" />
    </joint>

<link name="ball2">
        <visual>
            <geometry>
             <sphere radius="${hight/2}" />
            </geometry>         
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="BL_clolor">
                <color rgba="0.0 0.5 0.2 0.8" />
            </material>
        </visual>
        <collision>
        <geometry>
             <sphere radius="${hight/2}" />
            </geometry>         
        <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:sphere_inertial_matrix m="1" r="${hight/2}" />
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="L6" type="continuous">
        <parent link="base_link" />
        <child link="ball2" />
        <origin xyz="${-radius} 0 ${-hight/2.0-base_lenth/2.0}" />
    </joint>

</robot>